# Generated by Django 5.0.2 on 2025-07-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CloudConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("cloud_count", models.IntegerField(default=20)),
                ("dawn_color", models.CharField(default="#ffffff", max_length=7)),
                ("sunrise_color", models.CharField(default="#ffa500", max_length=7)),
                ("sunset_color", models.CharField(default="#ffc0cb", max_length=7)),
                ("animation_speed", models.FloatField(default=0.5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
